#!/bin/bash

set -eu # -x for verbose logging to ensemble debug-log

# some sort of a guard?

# Get the database settings; if not set, wait for this hook to be
# invoked again
database=`relation-get database`
if [ -z "$database" ] ; then
    exit 0 # wait for future handshake from database service unit
fi

user=`relation-get user`
password=`relation-get password`
host=`relation-get host`


ensemble-log "configuring drupal to work with the mysql service"

config_file_path="/etc/drupal/6/sites/default/dbconfig.php"
ensemble-log "Writing drupal config file $config_file_path"
cat > $config_file_path <<EOF
<?php
##
## database access settings in php format
##
\$dbuser='$user';
\$dbpass='$password';
\$basepath='';
\$dbname='$database';
\$dbserver='$host';
\$dbport='5432';
\$dbtype='pgsql';
?>
EOF
chown root:www-data $config_file_path
chmod 0640 $config_file_path

ensemble-log "Restart apache"
/etc/init.d/apache2 restart
