#!/bin/bash

set -eu # -x for verbose logging to ensemble debug-log

#config_file_path="/etc/wordpress/config-$hostname.php"
#if [ -f "$config_file_path" ] ; then
#    ensemble-log "Wordpress for site $config_file_path already Configured, exiting"
#    echo "Already Configured, Exiting"
#    exit 0 # already setup
#fi

# Get the database settings; if not set, wait for this hook to be
# invoked again
database=`relation-get database`
if [ -z "$database" ] ; then
    exit 0 # wait for future handshake from database service unit
fi

# Our protocol on this interface ensures that all or none of the
# settings are set. But we can verify the setting or the values if
# more error checking if desired.
user=`relation-get user`
password=`relation-get password`
host=`relation-get host`

ensemble-log "Writing config out to a testfile"
cat > /tmp/relation-config.txt <<EOF
DB_NAME: $database
DB_USER: $user
DB_PASSWORD: $password
DB_HOST: $host
EOF

ensemble-log "configuring drupal to work with the mysql service"

config_file_path="/etc/drupal/6/sites/default/dbconfig.php"
ensemble-log "Writing drupal config file $config_file_path"
cat > $config_file_path <<EOF
<?php
##
## database access settings in php format
##
\$dbuser='$user';
\$dbpass='$password';
\$basepath='';
\$dbname='$database';
\$dbserver='$host';
\$dbport='';
\$dbtype='mysql';
?>
EOF
chown root:www-data $config_file_path
chmod 0640 $config_file_path

ensemble-log "Restart apache"
/etc/init.d/apache2 restart
