#!/bin/bash

set -eu # -x for verbose logging to ensemble debug-log

#config_file_path="/etc/wordpress/config-$hostname.php"
#if [ -f "$config_file_path" ] ; then
#    ensemble-log "Wordpress for site $config_file_path already Configured, exiting"
#    echo "Already Configured, Exiting"
#    exit 0 # already setup
#fi

# Get the database settings; if not set, wait for this hook to be
# invoked again
database=`relation-get database`
if [ -z "$database" ] ; then
    exit 0 # wait for future handshake from database service unit
fi

# Our protocol on this interface ensures that all or none of the
# settings are set. But we can verify the setting or the values if
# more error checking if desired.
user=`relation-get user`
password=`relation-get password`
host=`relation-get host`

ensemble-log "Writing config out to a testfile"
cat > /tmp/relation-config.txt <<EOF
DB_NAME: $database
DB_USER: $user
DB_PASSWORD: $password
DB_HOST: $host
EOF

#ensemble-log "configuring drupal to work with the mysql service"
echo drupal6 drupal6/dbconfig-upgrade  boolean false | debconf-set-selections
echo drupal6 drupal6/dbconfig-reinstall  boolean false | debconf-set-selections
echo drupal6 drupal6/internal/skip-preseed boolean false | debconf-set-selections
echo drupal6 drupal6/dbconfig-install  boolean false | debconf-set-selections
echo drupal6 drupal6/mysql/app-pass password $password | debconf-set-selections
echo drupal6 drupal6/db/app-user string $user | debconf-set-selections
echo drupal6 drupal6/db/dbname string $database | debconf-set-selections
echo drupal6 drupal6/remote/host string $host | debconf-set-selections
echo drupal6 drupal6/remote/newhost string $host | debconf-set-selections

#echo drupal6 drupal6/database-type select mysql | debconf-set-selections
#echo drupal6 drupal6/mysql/method select unix socket | debconf-set-selections
#echo drupal6 drupal6/remote/port string | debconf-set-selections



DEBIAN_FRONTEND=noninteractive dpkg-reconfigure drupal6

ensemble-log "Restart apache"
/etc/init.d/apache2 restart
