#!/bin/bash

set -eu # -x for verbose logging to ensemble debug-log

if [ -L /etc/apache2/conf.d/drupal6.conf ]; then
  ensemble-log "Drupal site already configured, exiting"
  echo "Already Configured, Exiting"
  exit 0
fi

apt-get install -qqy debconf-utils 

ensemble-log "Installing default local mailer, postfix"
echo postfix postfix/main_mailer_type select 'Internet Site' | debconf-set-selections
echo postfix postfix/mail_name string $HOSTNAME | debconf-set-selections
DEBIAN_FRONTEND=noninteractive apt-get -y install -qq postfix

ensemble-log "Installing drupal with sane defaults"
echo drupal6 drupal6/dbconfig-upgrade  boolean false | debconf-set-selections
echo drupal6 drupal6/dbconfig-reinstall  boolean false | debconf-set-selections
echo drupal6 drupal6/internal/skip-preseed boolean false | debconf-set-selections
echo drupal6 drupal6/dbconfig-install  boolean false | debconf-set-selections
DEBIAN_FRONTEND=noninteractive apt-get -y install -qq --no-install-recommends drupal6

DEBIAN_FRONTEND=noninteractive apt-get -y install -qq --no-install-recommends php5-pgsql postgresql-client

ensemble-log "Configure apache vhost for the drupal site"
if [ -f /etc/drupal/6/apache.conf ]; then
  ln -sf /etc/drupal/6/apache.conf /etc/apache2/conf.d/drupal6.conf
fi

ensemble-log "Restart apache"
/etc/init.d/apache2 restart
